### ISSUE TITLE
Notifications Recieved on Submitted Reports

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#47]
Several organisations have notified me that they are receiving notifications for OVERDUE reports even tho they have submitted their report (or that their Project is completed).

**Comment by pfitzpaddy** [comment]
Furthermore, projects that are submitted with no data are receiving notifications also.

**Comment by pfitzpaddy** [comment]
Looks like this https://github.com/pfitzpaddy/ngm-reportEngine/pull/27 pull request introduced the issue. Might also be the problem causing opening of reports on projects that have already closed. I cant see the issue myself. Previously I used to print the JSON result before sending the emails to test.

**Comment by pfitzpaddy** [comment]
This report for January 2017 suggests it was submitted December 18, 2017 and there was still an alert for OVERDUE

**Comment by pfitzpaddy** [comment]
`0 5 20 * * root /home/ubuntu/nginx/www/ngm-reportEngine/tasks/reports/ngm_reporthub_reports_reminder.sh` has been temporarily removed from cron jobs, we will add that back when reviewed

**Comment by drfaustusfade** [comment]
the issue is in locations report_status, that is not updated on report report_status change so that on further filtering on locations retrieves wrong.

https://github.com/pfitzpaddy/ngm-reportEngine/pull/28

to update db so that locations statuses match report one on historical data next script
runs a couple of minutes on test machine

```javascript
db.report.find({report_status:'complete'}).forEach(function(r){
  db.location.find({report_id: r._id.valueOf() }).forEach(function(l){
    if (l.report_status && l.report_status !== 'complete'){
      l.report_status = 'complete';
      db.getCollection('location').save( l );
    }
  })
})
```

additionally added filtering by year for notification reminder so that only current reporting year notifications sent

**Comment by drfaustusfade** [comment]
tested in test on today's 27022018 moring backup, in data/test_notification folder on dropbox,  
no issues found at random selection
to allow test_mode print on test `testMode : true` setting is needed in email.js
